# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: e5356473798ca2ef9a353a66725ce2a43a1bd9112c73bbfadfb54237aeff8f39afecb7f64e77611339b2a8ab5cef6b1248d6bce5daeee01cf19774c911aac06a

test:
  secret_key_base: cbb6462ec5126d0a9f101311f2ccc7f6735a9e61ca5ebdaaa5a62a98476f921a9bff63ed518869fdec5f32a64e6308ccc88224a41b0229bea23eaa16007a50a6

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
